### PR TITLE
fix: Change create-database request to use new_database_name input (fixes #2)

### LINKED ISSUE #2: Input `new_database_name` is not used
Hi,

When running this action, I noticed the new database name I provided is not shown in the GitHub Action logs. The reason for this is the fact that the input is unused and the new database name is set to be `${{ github.ref_name }}` (line 70 in `action.yaml`) instead of the expected `${{ inputs.new_database_name }}`.

Happy to submit a PR for this! :)

### PR DESCRIPTION
**Pull request by tphbrok**

### CODE REVIEW

**Comment by notrab** [comment]
Hey @tphbrok 

Thanks for the PR! I was playing around with this at the weekend and noticed that some of my existing actions broke updating to this. Do you think it's worth doing something like we have for the group name for the database name?

```yml
        if [ -z "${{ inputs.group_name }}" ]; then
          GROUP_TO_USE=$GROUP_NAME
        else
          GROUP_TO_USE="${{ inputs.group_name }}"
        fi
```

Unless we document the ref_name to be passed in the input. What do you think?

**Comment by tphbrok** [comment]
@notrab Thanks for picking up this PR! 

Did the action break when you left `inputs.new_database_name` empty? Or some other scenario?

I agree that it shouldn't break easily, but in the end `new_database_name` is a required input. If you do wish to have a fallback for `new_database_name` in case it's missing, I'd say assigning `github.ref_name` to the `default` property of the `new_database_name` input is a better option than doing that in a shell script.

Let me know if you agree! :)

**Comment by alehechka** [comment]
I agree that setting the default value for `new_database_name` as `github.ref_name` is the right approach to keep this backwards compatible. Would be great if this could get merged in. Currently running into broken GHA runs on PR triggers because `github.ref_name` is formatted as `<pr#>/merge`.

Going to use @tphbrok's fork for the time being :/

**Comment by tphbrok** [comment]
@alehechka I had the exact same issue, where I was receiving an error because the new database name was invalid (as the Turso API didn't accept `<pr#>/merge`). 

I'll add `github.ref_name` as a default for `new_database_name` in my fork, optimistically assuming that that will be the accepted implementation.

**Comment by notrab** [comment]
@tphbrok happy to merge that change 🚀

**Comment by alehechka** [comment]
I also ran into an issue where subsequent runs would fail due to the database already existing from the first run. I created a fork that includes a new input to first check if the database exists and skip creation if so. Let me know if you'd be interested in these changes and I can open a PR.

https://github.com/alehechka/create-database-action/commit/bf73d9da2b3589c183b27f4ac82a3ab46ee209c5

**Comment by tphbrok** [comment]
@notrab Right, after some research I've found out that in GitHub Actions there's no support for anything other than plain strings in the `default` property of an input. :(

I've pushed a new commit to my fork to make `new_database_name` default to `pr-<pr#>` (since `<pr#>/merge` isn't accepted since only lowercase alphanumeric characters and dashes are allowed).

@alehechka I also ran into that issue, but due to the temporary nature of a PR in my use case, I've solved it by simply deleting and recreating the database instead of skipping its creation (which would also be a nice property to have in this action, something along the lines of a boolean called `overwrite` or `recreate`).

**Comment by alehechka** [comment]
I can say with strong authority that you can use github context as a default value and it will use the context variable when the input is not provided.

```yaml
new_database_name:
    description: "The new database name."
    required: true
    default: ${{ github.ref_name }}
```

**Comment by notrab** [comment]
So I think what we'd like to see here right now is that the `default` value is `github.ref_name`.

I'd rather not add code to the action that deals with specific naming conventions but relies on a previous step in the workflow (the original commit in this PR).

For example, we can change the value of the database by doing the following:

```yaml
name: Create Database for Branch
on: create

jobs:
  create_database:
    name: "Create Database"
    runs-on: ubuntu-latest
    steps:
      - name: Format ref_name
        run: echo "NEW_DATABASE_NAME=prefix_${{ github.ref_name }}" >> $GITHUB_ENV // DO WHATEVER HERE
      - name: Create Database
        uses: tursodatabase/create-database-action@v1
        with:
          organization_name: ${{ secrets.TURSO_ORGANIZATION_NAME }}
          api_token: ${{ secrets.TURSO_API_TOKEN }}
          existing_database_name: ${{ secrets.TURSO_DATABASE_NAME }}
          new_database_name: ${{ env.NEW_DATABASE_NAME }}
```

Do we all agree this is more agnostic?

**Comment by tphbrok** [comment]
@alehechka Thanks for clarifying, I concluded that it wasn't supported based on some forum posts online, but I haven't actually tried it.

@notrab I agree, I've reverted my changes and added the `default` property to the input. 

What now remains is the fact that relying on the default value of the `new_database_name` input will always result in an error in case of a PR workflow, because `<pr#>/merge` isn't accepted by the Turso API. Should that be taken into consideration (to provide a default that will be accepted)?

**Comment by notrab** [comment]
It seems like `<pr#>/merge` is a convention of your project or team that doesn't apply to everyone, am I right? If so, we should update the README to provide the example that shows how you can customise the database name in a previous step.

**Comment by tphbrok** [comment]
@notrab It's the GitHub default, as seen [in the documentation](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context):

> For pull requests, the format is <pr_number>/merge.

**Comment by notrab** [comment]
Ah! That makes sense. I tested this for new branches created but not PRs which would explain that confusion. Thanks for clearing that up.

That said, it highlights that this should perhaps remain agnostic. Some folks might do the action on a PR or branch which have their own name. Maybe the logic you had/have to conditionally check for PR prefix could still be used.

**Comment by tphbrok** [comment]
@notrab No problem!

I wanted to argue if we should even provide a default value for `new_database_name` (instead of relying on the API to error out when it's missing), but I realized that that would be a breaking change for folks using the action without having provided a value for the `new_database_name` input.

I've pushed another commit where the new database name defaults to `github.ref_name`, but gets reformatted from `<pr#>/merge` to `pr-<pr#>` in case of a PR workflow. What do you think? :)

**Comment by notrab** [comment]
@tphbrok I like this new approach. I was going to release this as a new tag anyways, so it wouldn't be so much of a breaking change if we wanted some newer behaviour.

The updated tag and docs can refer to `v1.1`. Wdyt?

**Comment by alehechka** [comment]
I like the idea of PR triggered workflows being able to properly create a database even when `new_database_name` is not provided. However, the current approach of formatting the name in a different, perhaps unexpected, way than the default is not sitting well with me. 

Another approach we could take is having multiple default values, one of them being the head ref name of the branch when the trigger was a PR.

This would look as follows:
```yaml
new_database_name:
    description: "The new database name."
    required: true
    default: ${{ github.head_ref || github.ref_name }}
```

The `github.head_ref` field is only available during PR triggered workflows as mentioned in the [docs](https://docs.github.com/en/actions/learn-github-actions/contexts#github-context), and by using `||` it would fallback to `github.ref_name` when not on a PR. It's definitely worth testing this on PR/push triggered workflows to make sure it works as expected.

**Comment by tphbrok** [comment]
@alehechka Despite having built the solution that doesn't sit well with you, I agree :'-)

Would `default: ${{ github.head_ref || github.ref_name }}` work for you @notrab ? It looks like we'll always have a valid value for `new_database_name` that way, without getting into regular expressions and string parsing (which we needed in my current solution).

**Comment by nkpgardose** [comment]
Would `${{ github.event.pull_request.base.ref }}` ideal for the fallback value? 

https://github.com/orgs/community/discussions/27154#discussioncomment-3254845

and `default` will lowercase and format spaces, special characters will default to `-` like a slugify. 👈 This is just an idea, and potentially might add it in the description of `new_database_name`

EDIT: Reading the comments. pr-<#pr-number> is good for all cases and easy to understand.

**Pull request closed without merging**
